---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 10.38.207.125 #192.168.1.103
    path: "/mnt/nfsshare/k8svolumes"